# Use the rails image as a base
FROM rails:4.2.1

WORKDIR /opt

RUN git clone https://a74199cc68e71ae2598eb5cb080261815dcd48b1@github.com/inquisi/backend.git

WORKDIR /opt/backend

RUN bundle install



