language: ruby
rvm:
  - 2.2.1
# Specify bundler args so that travis ignores Gemfile.lock and does not add
# the `--deployment` flag to the `bundle install` command it runs to install gems
bundler_args: " "
notifications:
  email: false
  # Our slack key -> backend channel
  # Might want to make this secret/encoded
  slack: inquisi:tN28qlf1uc3wVDVt0Uqvucha#backend
# Cache `bundle install` on travis
cache: bundler