language: ruby
rvm:
  - 2.2.1
# Specify bundler args so that travis ignores Gemfile.lock and does not add
# the `--deployment` flag to the `bundle install` command it runs to install gems
 bundler_args: