# Service name
backend:
  # Build at the current directory
  build: ./production-backend
  # link to other containers
  links:
    - mysql
  environment:
    MYSQL_DATABASE: inquisi_development
    VIRTUAL_HOST: api.inquisi.io
  command: /bin/bash production-backend/docker-compose.backend.sh
# Database
mysql:
  build: ./production-mysql
  environment:
    MYSQL_ROOT_PASSWORD: inquisi1837
    MYSQL_DATABASE: inquisi_development
# Web Server
nginxmod:
  build: ./production-nginx
  ports:
    - "80:80"
  command: nginx
  links:
    - backend